name: Release and Build Docker Image

on:
  # Release-please opens or updates a PR; we'll only finalize on merge
  pull_request:
    types: [closed]
    branches: [main]
  # (Optional) if you still want to run release-please checks on pushes:
  push:
    branches: [main]

jobs:
  release:
    name: Run Release Please
    runs-on: ubuntu-latest
    # This job runs on push or pull_request events, generating the release PR before merge.
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v3
        with:
          release-type: node
          # Adjust settings as needed
          bump-minor-pre-major: true
          package-name: "fleetsim"

  build-and-push-docker:
    name: Build and Push Docker image
    needs: release
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, 'chore(main): release')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/fleetsim
          # Optionally, use the new version from the release-please output:
          VERSION=$(node -p "require('./package.json').version")
          echo "Docker version: $VERSION"
          docker build -t $IMAGE_NAME:$VERSION .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/fleetsim
          VERSION=$(node -p "require('./package.json').version")
          docker push $IMAGE_NAME:$VERSION